### PR TITLE
Revert muon

### PR DESCRIPTION
**Pull request by wael444**
this PR will revert all the changes for muon following the fact that no matter what, until illiliti solves it, meson will always still be needed.

this will remove the need for muon at build time, as muon has still not been up-streamed in the KISS repositories yet.

also fixes some packages.

@ehawkvu , yajl is broken and i3 is broken and this is untested.
i will also ask you to put the current kiss-xorg branch into `muon` branch for the muon changes to be kept, my PR #86 should be merged into that branch as well.

### CODE REVIEW

**Comment by ehawkvu** [comment]
@wael444 Sorry it's taken so long to get to this PR. Are you saying that you'd like to just keep the other muon PR open so that once it's ready we can merge? 

Also, I have added `yajl` to this repo so that should be fine now. Is it worthwhile to investigate bumping `i3`'s version too?

**Comment by wael444** [comment]
> Are you saying that you'd like to just keep the other muon PR open so that once it's ready we can merge?

Yes. It isn't worthwhile to have a repository use a different build system as to the mainline repositories. One will still need meson for mesa and some packages, so why is it worth it to use meson when it can just be removed thanks to kiss orphans?

**Comment by ehawkvu** [comment]
That works for me -- also how do you feel about adding in pkg-config checks in a few of the packages under `extra/` to check for wayland? And if you have xwayland installed (with sway forked to support it) you shouldn't have to rebuild much, if anything besides mesa.

**Comment by wael444** [comment]
> to check for wayland?

I do this myself in my own repositories, having a Xorg repository also have the ability to work with Wayland is weird. It should have some discussion IMO.

Maybe under its own repository called 'xwayland', literally meant for both to be in use of some sort.. Idk.

**Comment by ehawkvu** [comment]
Sounds good to me. I'll open an issue.

**Pull request merged**
