### PR TITLE
xenocara

### PR DESCRIPTION
**Pull request by hovercats**
So, xenocara has now been mentioned several times on the irc, and theres seems to be some interest in porting this over to kiss, so here we are.

As of writing, ive not tested this any more than building it on my laptop which im currently writing on, and creating the buildscript on my desktop, and trying to launch it, only for it to freeze up my desktop, so this needs some more details as to whats needed to actually run this properly.

I fetched the patches from hyperbola (seeing as theyre moving to bsd, this is probably one of their steps towards this), which also gives us some referencces aswell for figuring this out.

Ill leave this as a draft for now, untill things are ready

edit: for those who do not know, xenocara is OpenBSD's fork of the Xorg server, and more. Should contain several security improvements and more.

### CODE REVIEW

**Comment by ehawkvu** [comment]
Just built it and am running it with success! I think there is something funky with the fonts though, since size 14 looks alot bigger than it usually does. Have tested both dwm & exwm and both work fine. I'm happy to merge when you feel this PR is ready 👍

Also thank you for looking into xenocara, I'm really glad that kiss-xorg will be able to offer 3 different X servers out of the box!

**Comment by hovercats** [comment]
sounds great! phoebos also had success with this.
I pushed some new commits, with something I suppose we want, like dri2 and 3. I know theyre enabled on `xorg-server` atleast, so id assume thats something thats wanted.
I also adjusted the rootless-modsetting patch to fit xenocara, but im not entierly sure wether its usefull or not? its a bit beyond my knowledge tbh.
if its not wanted/needed, we can simply remove it.

In any case, seeing as it works for you guys, I dont see why we cant merge now if everything is still in order.

the pleasure is all mine. its always great to kiss make some progress.

**Comment by ehawkvu** [comment]
I think it'd be interesting to revist Xenocara more indepth in the future, and see how much of Xorg we could replace, since it provides all of the libs/tools/apps/etc.

**Comment by hovercats** [comment]
Ive just shifted through the dirs, and it contains.. aloot of stuff to say the least.
everything X youd ever need, fontconfig even, aswell as mesa, pixman and more.
If im not mistaken, the sourcetree itself, should contain everything you need to get a working X server going.

we could probably have xenocara package initially be everything in one package, from libX*, mesa, header files and the x server.

**Pull request merged**
