### PR TITLE
apint & libsaveas: new package at git

### PR DESCRIPTION
**Pull request by wael444**
amazing paint program

please dont tell me i need esources please i cannot reclone and add and squash and rebase -i HEAD~2 please

### CODE REVIEW

**Comment by ehawkvu** [comment]
Why not just make the version & soures git?

Also I can't build this:

```
cc -std=c99 -pedantic -Wall -Wextra -Os -I/usr/X11R6/include -DVERSION=\"0.3.6\"   -c -o apint.o apint.c
apint.c:48:10: fatal error: saveas/saveas.h: No such file or directory
   48 | #include <saveas/saveas.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: apint.o] Error 1
```

**Comment by wael444** [comment]
Oh shit I forgot about a library it needs sorry

**Comment by wael444** [comment]
i love `git rebase`

**Comment by wael444** [comment]
https://github.com/alpheratz0/libsaveas/pull/2

**Comment by ehawkvu** [comment]
```
==> build <==
#!/bin/sh -e

export DESTDIR=$1

# Bundle libsaveas since nothing else uses this.
cd libsaveas
mkdir -p tmp
make DESTDIR="$PWD/tmp"
make DESTDIR="$PWD/tmp" PREFIX=/usr install
cd $OLDPWD

# Ensure that we can use the bundled libsaveas.
sed "/^INCS/s~$~ -I$PWD/libsaveas/tmp/usr/include/ ~" config.mk > _
mv -f _ config.mk
sed "/^LDFLAGS/s~$~ -L$PWD/libsaveas/tmp/usr/lib/~" config.mk > _
mv -f _ config.mk
sed "/^CFLAGS/s/$/ -static/" config.mk > _
mv -f _ config.mk

make
make PREFIX=/usr install

==> depends <==
libpng
libxcb
xcb-util-cursor
xcb-util-image
xcb-util-keysyms
xcb-util-wm

==> sources <==
git+https://github.com/alpheratz0/apint
git+https://github.com/alpheratz0/libsaveas libsaveas

==> version <==
git 1
```

**Comment by wael444** [comment]
sorry!! i wanted to do this originally but i got distracted doing other things, though; i thought bundling wasn't a KISS thing; as said by testuser.

**Pull request closed without merging**
