### PR TITLE
webkit and friends: add switches for using libsoup3

### PR DESCRIPTION
**Pull request by hovercats**
Reference #24

Adding a switch for all 3 browsers for libsoup3, except for `vimb-git` pkg,
as that would require to revert the PR that was recently merged.
I expect that patch to eventually break anyway, which is why I didnt add it.

also, `vimb` has `libsoup` in dep file, I would perhaps want to remove it, or comment it out.
We can assume users already have either libsoup/-3 installed already,
as its needed to build webkit anyway.

In my repo, I commented out libsoup in the dep file for webkit.
This is because I didnt want the package manager to force install either libsoup/-3.

If the users has for w/e reason chosen to uninstall libsoup,
the error messages is rather clear for both webkit2gtk, aswell as the browsers imo.

any thoughts on this @ehawkvu?

### CODE REVIEW

**Comment by wael444** [comment]
Why a switch? Why not simply only using it and dropping the outdated libsoup?

**Comment by hovercats** [comment]
I dont disagree, but it boils down to compability. There has been some ABI changes post libsoup 2.something.something..
Im unsure if the rest of the packages in the repo which still depends on `libsoup` package, is compatible with `libsoup3`.
All of these builds with both, but havent tested those Ive listed in #24

Youre ofcourse free to test this yourself, and see if everything works with libsoup3, so we can get rid of the extra package.

**Comment by wael444** [comment]
I mean, compiling webkit2gtk takes longer than Firefox, and I'd like to not use atk.

**Comment by ehawkvu** [comment]
Looks good, only thing I'd change is in webkit2gtk, I'd make the check for libsoup3 the same as in the other packages, ie using `pkg-config` instead of `kiss list`.

**Comment by ehawkvu** [comment]
Also I'd add a comment to each of the packages, explaining what the check is for - ex: "If libsoup3 is installed, switch webkit version to webkit2gtk-4.1"

**Comment by hovercats** [comment]
> Looks good, only thing I'd change is in webkit2gtk, I'd make the check for libsoup3 the same as in the other packages, ie using `pkg-config` instead of `kiss list`.

sure. I just used `kiss list`, for consistency sake, as that were already used.

> Also I'd add a comment to each of the packages, explaining what the check is for - ex: "If libsoup3 is installed, switch webkit version to webkit2gtk-4.1"

done!

Regarding removing libsoup from dep lists, whats your take on it?
`vimb-git` now explicitly requires libsoup3, unless we wanna patch it out with a switch, which would ultimately break down the line.
I was thinking in the line of if a user builds wekbit 4.0 for wyeb or surf, then decides to build `vimb-git` which would require a rebuild of webkit with libsoup3. On modern systems this is probably not too much of an issue, aside from being an annoyance.

Heres an my take on it anyway;
Removing `libsoup` from depends files (or atleast comment it out, so its more clear that its needed), this would avoid the package manager forcing libsoup2, even if libsoup3 is instead used. leaving users with an extra package which is no longer needed. (I know, users can use KISS_FORCE to remove it, but I would still consider this a inconvinience)
We could also make a post-build file on webkit or `vimb-git`, to clearify, so users might avoid having to rebuild webkit unneccessary.

Thoughts?

**Pull request merged**
