### PR TITLE
xrectsel: new package at 0.3.2

### PR DESCRIPTION
**Pull request by TAAPArthur**
Migrated packaged from community.

### CODE REVIEW

**Comment by ehawkvu** [comment]
I think upstream is dead. I did a quick checkout of this pr, and when trying to run `kiss d` it errors out.

**Comment by TAAPArthur** [comment]
My bad. Tried building locally before submitting the PR but was using a cached source. Update the source file.

**Comment by ehawkvu** [comment]
Also is there a particular reason this is in `xorg/`? Otherwise lgtm.

**Comment by TAAPArthur** [comment]
I don't have a strong opinion on where it goes. Thought it fit under "other misc software for X" but I can see the argument for putting it under community. I can move it if you prefer.

**Pull request merged**
