### PR TITLE
tinyx: make libXdmcp a makedep

### PR DESCRIPTION
**Pull request by hovercats**
it seems we can simply disable the usabe of libXdmcp.

might need some more testing.
perhaps @kyx0r has some input on this.

on my end it does seem to work fine.

If theres no issue, Ill add the removal of `libXdmcp` in this PR aswell, as nothing else needs it.

### CODE REVIEW

**Comment by kyx0r** [comment]
Hi, I'm on vacation. I will be getting back on next week.

**Comment by ehawkvu** [comment]
If it does turn out successful, and kyx0r doesn't notice anything, feel free to remove `libXdmcp` in this PR as well.

**Comment by hovercats** [comment]
ok so Ive been doing some testing today, after spending to week to rebuild my system and fixing errors'

Ive since not been able to build tinyx without `libXdmcp` installed.
it will instead complain about missing `Xdmcp.h` file.

Im starting to suspect I got ahead of myself.
I guess I added the flags in the first commit, and got tinyx to build, and it did no longer link to `libXdmcp`. which was what I was looking for.
At that time, I assume libXdmcp also was installed, without me realising it atm. 

So as far as I can tell from this, is we cannot get rid of `libXdmcp` entierly, but we can make it a make dependency.
this is atleast what I came up with some messing with it.
@kyx0r might chime in with some more stuff here if he finds more than I do.


Also, `automake` is missing from the depends file.
Ill add it into this pr too.

**Comment by hovercats** [comment]
@kyx0r, did you ever get to test this?

in any case, Ive had no issues on my end from using this for around a month now.

btw, `linux-headers` and `pkgconf` is missing in depfile.
I can add them myself, either here or in a separate PR. or w/e youd like @ehawkvu.

**Comment by kyx0r** [comment]
@hovercats Hi, no did not test it. If it runs fine without libXdmcp, then I guess this PR is fine.

However, one thing I am concerned about is this:

```
$ ldd /bin/Xfbdev
	/lib/ld-musl-x86_64.so.1 (0x7fa2ac2a0000)
	libXfont.so.1 => /lib/libXfont.so.1 (0x7fa2ac132000)
	libXdmcp.so.6 => /lib/libXdmcp.so.6 (0x7fa2ac12a000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7fa2ac2a0000)
	libfreetype.so.6 => /lib/libfreetype.so.6 (0x7fa2ac051000)
	libz.so.1 => /lib/libz.so.1 (0x7fa2ac037000)
	libfontenc.so.1 => /lib/libfontenc.so.1 (0x7fa2ac02c000)
	libpng16.so.16 => /lib/libpng16.so.16 (0x7fa2abfe0000)
	libharfbuzz.so.0 => /lib/libharfbuzz.so.0 (0x7fa2abe85000)
```

You can see that it links to libXdmcp.so, which tells me that the program will fail to
start if removed. Thats why im not sure how its working on your end.

**Comment by hovercats** [comment]
it, does out of the box link to libXdmcp, yes.
but not if you disable both xdmcp, and xdm-auth-1 like in the first commit.

its really strange, as one would assume it builds without it.
but it fails, and complain about Xdmcp.h is missing.
maybe its just a minor patch away, I dunno. havent looked too much at it tbh.

I also built mine static earlier today, if that is of any interest.

**Comment by hovercats** [comment]
can this be merged now, or are we still gonna wait for @kyx0r to do his thing?

Ive also managed to build tinyx without autotool, by including the neccessary files. would this be of interest @ehawkvu? in any case, I can make a pr for it if you like.

**Comment by ehawkvu** [comment]
@hovercats I can merge it now and we can work on autotools later.

**Comment by hovercats** [comment]
ok, cool.

**Pull request merged**
