### PR TITLE
xorg-server: 21.1.0

### PR DESCRIPTION
**Pull request by ioraff**
The meson build in the tarball at x.org is broken, but not in the tarball at gitlab (which also removes the autotools build). I imagine this will be fixed with 21.1.1.

With the exception of some font sizing issues in dwm (so this may be an Xft issue), this build, which is basically one-to-one with the previous autotools build, works for me.

### CODE REVIEW

**Comment by ehawkvu** [comment]
Were you able to resolve the font issue? I noticed the same thing with the testing package.

I'm happy to merge once I figure out how to fix the issue with dwm.

**Comment by ioraff** [comment]
Not exactly. For the time being, I've just scaled my monospace font in fonts.conf--my issue with dwm was that my monospace size blew up while font-awesome remained as it was.

**Comment by ehawkvu** [comment]
Interesting. Testing dwm, dmenu, and st, only dwm and dmenu have the font issue, st seems unaffected (I am using a good number of patches though).

I'll test with some other software.

**Comment by ehawkvu** [comment]
@ioraff I was able to fix the font scaling issue using Arch's dpi calcuation patch. If you want to update xorg-server to 21.1.1 and add in the patch, I'll merge.

**Comment by ioraff** [comment]
I've since switched to wayland. Thanks, though.

**Pull request closed without merging**
